schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type ModelPendingSubmissionConnection @aws_api_key @aws_cognito_user_pools @aws_iam {
  items: [PendingSubmission]!
  nextToken: String
}

type ModelSharedChecklistConnection @aws_api_key @aws_cognito_user_pools @aws_iam {
  items: [SharedChecklist]!
  nextToken: String
}

type ModelSharedPlaneConnection @aws_api_key @aws_cognito_user_pools @aws_iam {
  items: [SharedPlane]!
  nextToken: String
}

type Mutation {
  createPendingSubmission(condition: ModelPendingSubmissionConditionInput, input: CreatePendingSubmissionInput!): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam
  createSharedChecklist(condition: ModelSharedChecklistConditionInput, input: CreateSharedChecklistInput!): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam
  createSharedPlane(condition: ModelSharedPlaneConditionInput, input: CreateSharedPlaneInput!): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam
  deletePendingSubmission(condition: ModelPendingSubmissionConditionInput, input: DeletePendingSubmissionInput!): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam
  deleteSharedChecklist(condition: ModelSharedChecklistConditionInput, input: DeleteSharedChecklistInput!): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam
  deleteSharedPlane(condition: ModelSharedPlaneConditionInput, input: DeleteSharedPlaneInput!): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam
  updatePendingSubmission(condition: ModelPendingSubmissionConditionInput, input: UpdatePendingSubmissionInput!): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam
  updateSharedChecklist(condition: ModelSharedChecklistConditionInput, input: UpdateSharedChecklistInput!): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam
  updateSharedPlane(condition: ModelSharedPlaneConditionInput, input: UpdateSharedPlaneInput!): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam
}

type PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam {
  createdAt: AWSDateTime!
  id: ID!
  image: String
  manufacturer: String!
  name: String!
  phases: String!
  sim: String
  status: String!
  submittedBy: String
  type: String!
  updatedAt: AWSDateTime!
}

type Query {
  getPendingSubmission(id: ID!): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam
  getSharedChecklist(id: ID!): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam
  getSharedPlane(id: ID!): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam
  listPendingSubmissions(filter: ModelPendingSubmissionFilterInput, limit: Int, nextToken: String): ModelPendingSubmissionConnection @aws_api_key @aws_cognito_user_pools @aws_iam
  listSharedChecklists(filter: ModelSharedChecklistFilterInput, limit: Int, nextToken: String): ModelSharedChecklistConnection @aws_api_key @aws_cognito_user_pools @aws_iam
  listSharedPlanes(filter: ModelSharedPlaneFilterInput, limit: Int, nextToken: String): ModelSharedPlaneConnection @aws_api_key @aws_cognito_user_pools @aws_iam
}

type SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam {
  createdAt: AWSDateTime!
  id: ID!
  phases: String!
  planeId: String!
  updatedAt: AWSDateTime!
}

type SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam {
  createdAt: AWSDateTime!
  id: ID!
  image: String!
  manufacturer: String!
  name: String!
  planeId: String!
  sim: String
  sortOrder: Int
  type: String!
  updatedAt: AWSDateTime!
}

type Subscription {
  onCreatePendingSubmission(filter: ModelSubscriptionPendingSubmissionFilterInput): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["createPendingSubmission"])
  onCreateSharedChecklist(filter: ModelSubscriptionSharedChecklistFilterInput): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["createSharedChecklist"])
  onCreateSharedPlane(filter: ModelSubscriptionSharedPlaneFilterInput): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["createSharedPlane"])
  onDeletePendingSubmission(filter: ModelSubscriptionPendingSubmissionFilterInput): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["deletePendingSubmission"])
  onDeleteSharedChecklist(filter: ModelSubscriptionSharedChecklistFilterInput): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["deleteSharedChecklist"])
  onDeleteSharedPlane(filter: ModelSubscriptionSharedPlaneFilterInput): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["deleteSharedPlane"])
  onUpdatePendingSubmission(filter: ModelSubscriptionPendingSubmissionFilterInput): PendingSubmission @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["updatePendingSubmission"])
  onUpdateSharedChecklist(filter: ModelSubscriptionSharedChecklistFilterInput): SharedChecklist @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["updateSharedChecklist"])
  onUpdateSharedPlane(filter: ModelSubscriptionSharedPlaneFilterInput): SharedPlane @aws_api_key @aws_cognito_user_pools @aws_iam @aws_subscribe(mutations : ["updateSharedPlane"])
}

enum ModelAttributeTypes {
  _null
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
}

enum ModelSortDirection {
  ASC
  DESC
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input CreatePendingSubmissionInput {
  id: ID
  image: String
  manufacturer: String!
  name: String!
  phases: String!
  sim: String
  status: String!
  submittedBy: String
  type: String!
}

input CreateSharedChecklistInput {
  id: ID
  phases: String!
  planeId: String!
}

input CreateSharedPlaneInput {
  id: ID
  image: String!
  manufacturer: String!
  name: String!
  planeId: String!
  sim: String
  sortOrder: Int
  type: String!
}

input DeletePendingSubmissionInput {
  id: ID!
}

input DeleteSharedChecklistInput {
  id: ID!
}

input DeleteSharedPlaneInput {
  id: ID!
}

input ModelBooleanInput {
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  eq: Boolean
  ne: Boolean
}

input ModelFloatInput {
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  between: [Float]
  eq: Float
  ge: Float
  gt: Float
  le: Float
  lt: Float
  ne: Float
}

input ModelIDInput {
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  beginsWith: ID
  between: [ID]
  contains: ID
  eq: ID
  ge: ID
  gt: ID
  le: ID
  lt: ID
  ne: ID
  notContains: ID
  size: ModelSizeInput
}

input ModelIntInput {
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  between: [Int]
  eq: Int
  ge: Int
  gt: Int
  le: Int
  lt: Int
  ne: Int
}

input ModelPendingSubmissionConditionInput {
  and: [ModelPendingSubmissionConditionInput]
  createdAt: ModelStringInput
  image: ModelStringInput
  manufacturer: ModelStringInput
  name: ModelStringInput
  not: ModelPendingSubmissionConditionInput
  or: [ModelPendingSubmissionConditionInput]
  phases: ModelStringInput
  sim: ModelStringInput
  status: ModelStringInput
  submittedBy: ModelStringInput
  type: ModelStringInput
  updatedAt: ModelStringInput
}

input ModelPendingSubmissionFilterInput {
  and: [ModelPendingSubmissionFilterInput]
  createdAt: ModelStringInput
  id: ModelIDInput
  image: ModelStringInput
  manufacturer: ModelStringInput
  name: ModelStringInput
  not: ModelPendingSubmissionFilterInput
  or: [ModelPendingSubmissionFilterInput]
  phases: ModelStringInput
  sim: ModelStringInput
  status: ModelStringInput
  submittedBy: ModelStringInput
  type: ModelStringInput
  updatedAt: ModelStringInput
}

input ModelSharedChecklistConditionInput {
  and: [ModelSharedChecklistConditionInput]
  createdAt: ModelStringInput
  not: ModelSharedChecklistConditionInput
  or: [ModelSharedChecklistConditionInput]
  phases: ModelStringInput
  planeId: ModelStringInput
  updatedAt: ModelStringInput
}

input ModelSharedChecklistFilterInput {
  and: [ModelSharedChecklistFilterInput]
  createdAt: ModelStringInput
  id: ModelIDInput
  not: ModelSharedChecklistFilterInput
  or: [ModelSharedChecklistFilterInput]
  phases: ModelStringInput
  planeId: ModelStringInput
  updatedAt: ModelStringInput
}

input ModelSharedPlaneConditionInput {
  and: [ModelSharedPlaneConditionInput]
  createdAt: ModelStringInput
  image: ModelStringInput
  manufacturer: ModelStringInput
  name: ModelStringInput
  not: ModelSharedPlaneConditionInput
  or: [ModelSharedPlaneConditionInput]
  planeId: ModelStringInput
  sim: ModelStringInput
  sortOrder: ModelIntInput
  type: ModelStringInput
  updatedAt: ModelStringInput
}

input ModelSharedPlaneFilterInput {
  and: [ModelSharedPlaneFilterInput]
  createdAt: ModelStringInput
  id: ModelIDInput
  image: ModelStringInput
  manufacturer: ModelStringInput
  name: ModelStringInput
  not: ModelSharedPlaneFilterInput
  or: [ModelSharedPlaneFilterInput]
  planeId: ModelStringInput
  sim: ModelStringInput
  sortOrder: ModelIntInput
  type: ModelStringInput
  updatedAt: ModelStringInput
}

input ModelSizeInput {
  between: [Int]
  eq: Int
  ge: Int
  gt: Int
  le: Int
  lt: Int
  ne: Int
}

input ModelStringInput {
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  beginsWith: String
  between: [String]
  contains: String
  eq: String
  ge: String
  gt: String
  le: String
  lt: String
  ne: String
  notContains: String
  size: ModelSizeInput
}

input ModelSubscriptionBooleanInput {
  eq: Boolean
  ne: Boolean
}

input ModelSubscriptionFloatInput {
  between: [Float]
  eq: Float
  ge: Float
  gt: Float
  in: [Float]
  le: Float
  lt: Float
  ne: Float
  notIn: [Float]
}

input ModelSubscriptionIDInput {
  beginsWith: ID
  between: [ID]
  contains: ID
  eq: ID
  ge: ID
  gt: ID
  in: [ID]
  le: ID
  lt: ID
  ne: ID
  notContains: ID
  notIn: [ID]
}

input ModelSubscriptionIntInput {
  between: [Int]
  eq: Int
  ge: Int
  gt: Int
  in: [Int]
  le: Int
  lt: Int
  ne: Int
  notIn: [Int]
}

input ModelSubscriptionPendingSubmissionFilterInput {
  and: [ModelSubscriptionPendingSubmissionFilterInput]
  createdAt: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  image: ModelSubscriptionStringInput
  manufacturer: ModelSubscriptionStringInput
  name: ModelSubscriptionStringInput
  or: [ModelSubscriptionPendingSubmissionFilterInput]
  phases: ModelSubscriptionStringInput
  sim: ModelSubscriptionStringInput
  status: ModelSubscriptionStringInput
  submittedBy: ModelSubscriptionStringInput
  type: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
}

input ModelSubscriptionSharedChecklistFilterInput {
  and: [ModelSubscriptionSharedChecklistFilterInput]
  createdAt: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  or: [ModelSubscriptionSharedChecklistFilterInput]
  phases: ModelSubscriptionStringInput
  planeId: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
}

input ModelSubscriptionSharedPlaneFilterInput {
  and: [ModelSubscriptionSharedPlaneFilterInput]
  createdAt: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  image: ModelSubscriptionStringInput
  manufacturer: ModelSubscriptionStringInput
  name: ModelSubscriptionStringInput
  or: [ModelSubscriptionSharedPlaneFilterInput]
  planeId: ModelSubscriptionStringInput
  sim: ModelSubscriptionStringInput
  sortOrder: ModelSubscriptionIntInput
  type: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
}

input ModelSubscriptionStringInput {
  beginsWith: String
  between: [String]
  contains: String
  eq: String
  ge: String
  gt: String
  in: [String]
  le: String
  lt: String
  ne: String
  notContains: String
  notIn: [String]
}

input UpdatePendingSubmissionInput {
  id: ID!
  image: String
  manufacturer: String
  name: String
  phases: String
  sim: String
  status: String
  submittedBy: String
  type: String
}

input UpdateSharedChecklistInput {
  id: ID!
  phases: String
  planeId: String
}

input UpdateSharedPlaneInput {
  id: ID!
  image: String
  manufacturer: String
  name: String
  planeId: String
  sim: String
  sortOrder: Int
  type: String
}
